#!/usr/bin/env python
import os, sys, subprocess
import xml.etree.ElementTree as ET
from optparse import OptionParser, OptionGroup
from patternHmm import generate_model_file

# TO DO:
#-- Add options to modify default transition probs when generating pattern file.
#   -- Perhaps: -MI 0.2 to specify that match to insert should be 0.2 instead of 0.3.
#-- Incorporate the strength of each motif into pHMM.
#-- Why are nearby patterns merged? looks like 214_1 is a good pattern merged with a bad one. Don't want this behaviour.

__author__ = 'David Curran'
__version__ = '1.1'


def run_mast(memeFile, seqFile, outputDir, eValue, dnaSeq=True):
    if not os.path.isdir(outputDir):
        os.makedirs(outputDir)
    args = ['mast', memeFile, seqFile, '-oc', outputDir, '-ev', str(float(eValue))]
    if dnaSeq: args.append('-dna')
    print '\nStarting MAST with the command:', ' '.join(args)
    try:
        retcode = subprocess.call(args)
        if retcode != 0:
            raise RuntimeError("MAST returned with the abnormal code %i"%retcode)
    except OSError:
        raise RuntimeError("Figmop requires that 'mast' is installed and available from the command line")
def create_pattern_file(model_len, model_path, min_matches, max_genome_region, meme_file):
    if max_genome_region == 0: max_genome_region = 40000
    mm_str = 'min_matches = %i' % min_matches
    ms_str = 'max_genome_region = %i' % max_genome_region
    mf_str = "meme_file = '%s'" % meme_file
    attribs_str = '\n'.join((mm_str, ms_str, mf_str))
    generate_model_file(model_len, model_path, attribs_str)


class MotifPatterns(object):
    """Parses the results of running MAST on some sequence file, searching for the
    patterns defined by the model argument. Any patterns detected can be printed
    with the print_patterns() method, or the sequences corresponding to those
    patterns can be extracted, and have MAST run on them using the
    run_mast_on_patterns() method. This class takes a minimum of 2 arguments on
    instanciation, the path to some MAST output, and a model describing some pattern
    of motifs. It also allows for a specified minimum number of motifs in a valid
    pattern, and the path to the sequence file that generated the given MAST output.
    This software works with MAST version 4.5.0 and 4.10.1; it may not with others."""
    def __init__(self, mastFile, model, sequenceFile=None, min_matches=None,
                 sequence_padding=0):
        self.min_matches = min_matches
        self.seq_pad = sequence_padding
        self.motifLengths = {}
        self.sequences = {}
        mastFile = self._validateMastPath(mastFile)
        self._parseMastFile(mastFile)
        if sequenceFile:
           self.sequenceFile = sequenceFile 
        self._findPatterns(model)

    # # # # #  Public Methods  # # # # #
    def run_mast_on_patterns(self, memeFile, maxSize=40000, e_value=10.0,
                          outputDir='mast_out', outputSeqsFilename=False):
        seqNames = tuple(seq for seq in self.sequences if self.sequences[seq]['matches'])
        if not seqNames:
            print "Error: Cannot run MAST, as there were no matches found to the given model."
            return False
        seqsDict = self._generateSeqsDict(self.sequenceFile, seqNames)
        if not seqsDict: return False
        tempSeqFile = self._writeTempSequenceFile(outputDir, seqNames, seqsDict, maxSize)
        run_mast(memeFile, tempSeqFile, outputDir, e_value)
        print 'Finished running MAST, cleaning up files...'
        if outputSeqsFilename: 
            self._outputMastHits(tempSeqFile, outputSeqsFilename, outputDir)
        os.remove(tempSeqFile)
    
    def print_patterns(self):
        """Prints the patterns found by the model in the MAST results."""
        numSeqs, totalMatches = 0, 0
        for seqName in sorted(self.sequences):
            numMatches = len(self.sequences[seqName]['matches'])
            if numMatches == 0: continue
            totalMatches += numMatches
            numSeqs += 1
            s = '\nFound %i matches in %s' % (numMatches, seqName)
            print s
            print '-' * len(s)
            for (start, end), states, seq in self.sequences[seqName]['matches']:
                self._printMatch(start, end, states, seq)
        print '\nFound %i matches total in %i sequences.\n' % (totalMatches, numSeqs)

    # # # # #  Private Methods  # # # # #
    def _findPatterns(self, model):
        """Fills out the 'matches' attribute for each entry in the
        self.sequences object by searching for motif patterns using
        the hidden Markov model."""
        found = 0
        print "Searching MAST output for patterns..."
        for atts in self.sequences.values():
            matches = model.find_matches(atts['sequence'], minimumMatches=self.min_matches,
                                         cleanSequence=False)
            negMatches = model.find_matches(atts['negSequence'], minimumMatches=self.min_matches,
                                            cleanSequence=False)
            atts['matches'] = self._parseBoundaries(matches, negMatches, atts)
            found += len(atts['matches'])
        print "Found %i total matches that satisfied the pattern." % found
    def _validateMastPath(self, mastFile):
        if os.path.isfile(mastFile):
            if mastFile.endswith('.xml'):
                return os.path.abspath(mastFile)
            mastFile = os.path.dirname(mastFile)
        if os.path.isdir(mastFile):
            contents = os.listdir(mastFile)
            for fname in contents:
                if fname.endswith('.xml'):
                    return os.path.abspath(os.path.join(mastFile, fname))
        raise IOError("Could not find a suitable MAST output .xml at or around %s" % mastFile)

    # # #  Outputting Methods
    def _printMatch(self, start, end, states, seq):
        maxWidth = max(map(len, seq))
        strFmt = '%%%is' % maxWidth
        s = '(%i) ' % start
        e = ' (%i)' % end
        states = ' '*len(s) + ','.join(strFmt % state for state in states) + ' '*len(e)
        seq = s + ','.join(strFmt % symb for symb in seq) + e
        for i in xrange(0, len(seq), 60):
            print seq[i:i+60]
            print states[i:i+60]
            print
    # # #  Parsing results
    def _parseBoundaries(self, matches, negMatches, atts):
        allMatches = []
        def calcBoundaries(states, ind, seq, starts):
            start = starts[ind]
            end = starts[ind + len(seq) - 1] + self.motifLengths[seq[-1]]
            return ((start, end), states, seq)
        def calcNegBoundaries(states, ind, seq, starts):
            start = starts[ind]
            end = starts[ind + len(seq) - 1] - self.motifLengths[seq[-1]]
            return ((start, end), states, seq)
        for states, (ind, seq) in zip(*matches):
            allMatches.append(calcBoundaries(states, ind, seq, atts['starts']))
        for states, (ind, seq) in zip(*negMatches):
            allMatches.append(calcNegBoundaries(states, ind, seq, atts['negStarts']))
        return allMatches

    def _parseMastFile(self, mastFile):
        """Fills out self.sequences self.motifLengths, and self.sequenceFile."""
        try:
            data = ET.parse(mastFile).getroot()
            motifs = data.find('motifs')
            self.motifLengths = dict((m.attrib['num'], 3*int(m.attrib['width']))
                                     for m in motifs.findall('motif'))
            self.sequences = {}
            seqs = data.find('sequences')
            self.sequenceFile = seqs.find('database').attrib['source']
            for sequence in seqs.findall('sequence'):
                seq_name = ' '.join(( "%s %s"%(sequence.attrib['name'], sequence.attrib.get('comment', '')) ).split())
                for_seq = []; neg_seq = []
                for_starts = []; neg_starts = []
                for seg in sequence.findall('seg'):
                    for hit in seg.findall('hit'):
                        strand = hit.attrib['strand']
                        pos = int(hit.attrib['pos']) - 1
                        m = hit.attrib['motif'][6:]
                        if strand == 'forward':
                            for_seq.append(m)
                            for_starts.append(pos)
                        else:
                            neg_seq.append(m)
                            neg_starts.append(pos + self.motifLengths[m])
                self.sequences[seq_name] = {'sequence':for_seq, 'negSequence':neg_seq[::-1],
                                        'starts':for_starts, 'negStarts':neg_starts[::-1]}
        except:
            print "\nIOError: encountered the following error attempting to parse the MAST .xml file at %s" % mastFile
            raise
        
    # # #  Methods to run MAST.
    def _generateSeqsDict(self, sequenceFile, seqNames):
        seqsDict = {}
        print 'Loading sequences from %s...\n' % sequenceFile
        seqs = loadfasta(sequenceFile, onlyThese=seqNames)
        for seqname in seqNames:
            if seqname in seqs:
                seqsDict[seqname] = seqs[seqname]
            else:
                print "Error: A sequence named '%s' was found in the MAST results but could not be found in the sequence file %s." % (seqname, sequenceFile)
                print "       MAST sometimes modifies the names of the sequences, for example replacing multiple consecutive spaces with a single one. You may have to simplify the names in %s and try again." % sequenceFile
                return False
        return seqsDict
    def _writeTempSequenceFile(self, outputDir, seqNames, seqsDict, maxSize):
        buff = []
        tempName = 'temp_mast_seq_file'
        for seqName in seqNames:
            for i, match in enumerate(self.sequences[seqName]['matches']):
                start, end = sorted(match[0])
                if (end - start) > maxSize:
                    continue
                start = max(0, start-self.seq_pad)
                end = min(len(seqsDict[seqName]), end+self.seq_pad)
                buff.append('>%s_%i\n%s\n' % (seqName, i+1, seqsDict[seqName][start:end]))
        if not os.path.isdir(outputDir): os.makedirs(outputDir)
        tempName = outputDir + '/' + tempName
        if os.path.isfile(tempName + '.fa'):
            i = 1
            while os.path.isfile(tempName + '_%i.fa'%i): i += 1
            tempName += '_%i.fa'%i
        else: tempName += '.fa'
        with open(tempName, 'wb') as f:
            f.write(''.join(buff))
        return tempName
    def _getMastHitNames(self, mastFile):
        data = ET.parse(mastFile).getroot()
        seqs = data.find('sequences')
        names = [("%s %s"%(seq.attrib['name'], seq.attrib['comment'])).strip() for seq in seqs.findall('sequence')]
        return names
    def _outputMastHits(self, tempSeqFile, outputSeqsFilename, outputDir):
        buff = []
        seqs = loadfasta(tempSeqFile)
        mastFile = os.path.join(outputDir, 'mast.xml')
        hitNames = self._getMastHitNames(mastFile)
        for name in hitNames:
            if name in seqs:
                baseName, _, num = name.rpartition('_')
                start,end = self.sequences[baseName]['matches'][int(num)-1][0]
                if start < end:
                    sequence = seqs[name]
                    start = max(0, start-self.seq_pad)
                    end = start + len(sequence) - 1
                else:
                    sequence = invcomplement(seqs[name])
                    end = max(0, end-self.seq_pad)
                    start = end + len(sequence) - 1
                buff.append('>%s--%i-%i\n%s\n' % (name, start, end, sequence))
            else:
                print "Error: Couldn't find sequence named %s in %s." % (name, tempSeqFile)
                print "       MAST sometimes modifies the names of the sequences, for example replacing consecutive spaces with a single one. You may have to simplify the names in the genome file."
                return False
        
        outFile = os.path.join(outputDir, outputSeqsFilename)
        with open(outFile, 'wb') as f:
            f.write(''.join(buff))
        print "\nWrote %i sequences to %s\n" % (len(buff), outFile)


# # # # # # # # # #  Functions from molecbio.sequ  # # # # # # # # # #
complement = {'A':'T','T':'A','C':'G','G':'C','U':'A'}
def loadfasta(filepath, onlyThese=[]):
    """Returns a dict from the file object: {seqname1: str(sequence1)...}
    If onlyThese is a list of strings, only those sequences that start
    with a string in that list will be collected."""
    if onlyThese:
        onlyThese = tuple(onlyThese)
    seqs, buff, curName = {}, [], None
    with open(filepath, 'rb') as f:
        for line in f:
            if line.startswith('>'):
                if buff:
                    seqs[curName] = ''.join(buff)
                    buff = []
                curName = ' '.join(line[1:].split())
                if onlyThese and not curName.startswith(onlyThese):
                    curName = None
            else:
                if not curName: continue
                line = line.strip()
                if line: buff.append(line.upper())
    if buff and curName:
        seqs[curName] = ''.join(buff)
    return seqs
def invcomplement(sequence):
    return ''.join([complement.get(c,'N') for c in sequence.upper()][::-1])
# # # # # # # # # # #  Functions to parse MAST xml file  # # # # # # # # # # # #
# In both functions the sequence name is split and forced to be space-separated
# because MAST sometimes handles spaces and tabs oddly.
def extract_seqs(mast_dir, seq_file, output_file):
    mast_xml = os.path.join(mast_dir, 'mast.xml')
    if not os.path.isfile(mast_xml):
        print 'Figmop runtime error: could not find a MAST xml file in %s' % mast_dir
        exit()
    names = get_names(mast_xml)
    print 'Loading sequences from %s...' % (seq_file)
    seqs = loadfasta(seq_file, names)
    buff = []
    for name in names:
        if name not in seqs:
            print 'Figmop runtime error: the MAST hit %s was not found in the sequence file %s' % (name, seq_file)
            exit()
        buff.append('>%s\n%s\n' % (name, seqs[name]))
    with open(output_file, 'w') as f:
        f.write('\n'.join(buff))
    print 'Saved %i sequences to %s' % (len(names), output_file)
def get_names(mast_xml):
    data = ET.parse(mast_xml).getroot()
    seqs = data.find('sequences')
    names = [' '.join(( "%s %s"%(seq.attrib['name'], seq.attrib.get('comment', '')) ).split()) for seq in seqs.findall('sequence')]
    return names


# # # # # # # # # #  Command Line Wrapper  # # # # # # # # # #
def setup_parser():
    usage = "There are 3 different ways to run Figmop; for more details please read the tutorial file at https://github.com/dave-the-scientist/figmop\n\nRun Figmop on protein sequences with:\n\t%prog MEME_FILE --prot PROT_FILE [options]\n\nGenerate a pattern file with:\n\t%prog --generate_pattern_file LENGTH [options]\n\nRun Figmop on a genome with:\n\t%prog PATTERN_FILE GENOME_FILE GENOME_MAST_DIR [options]"
    version_str = "%%prog %s" % __version__
    parser = OptionParser(usage=usage, version=version_str)
    parser.set_defaults(output_dir='mast_out', e_value=0.01, hits_filename='hits.fa',
                        prot_file='',
                        generate_pattern_file=0, pattern_file_path='pattern_file.py',
                        sequence_padding=0, default_mast_xml='mast.xml',
                        max_genome_region=0, min_matches=0, meme_file='')

    parser.add_option('-o', '--output_dir', dest='output_dir',
                      metavar='DIR', help='write output to DIR [default: %default]')
    parser.add_option('-e', '--e_value', dest='e_value', type='float',
                      help='max E-value for hits [default: %default] NOTE: this is derived from the length of the gene and the quality of the motif matches. It has nothing to do with adherance to the pattern.')
    parser.add_option('-n', '--hits_filename', dest='hits_filename',
                      help='name for the file containing fasta formatted hits [default: %default]')
    
    prot_group = OptionGroup(parser, 'Run on protein sequences', 'To run Figmop on protein sequences supply the --prot flag with some sequence file, followed by the path to some meme.txt file. This mode respects the --output_dir, --e_value, and --hits_filename options. This will run MAST and extract the sequences; as such it does not actually respect any pattern, and so does not require a pattern file.')
    prot_group.add_option('--prot', dest='prot_file',
                          help='run Figmop on protein sequences')
    parser.add_option_group(prot_group)
    
    generate_pattern_file = OptionGroup(parser, 'Generate a pattern file', "To generate a pattern file, supply the --generate_pattern_file flag with some length, and optionally a file name. Also, any of the 'Model options' given will be filled out as default values in the pattern file. This will not run Figmop.")
    generate_pattern_file.add_option('-g', '--generate_pattern_file', type='int',
                          dest='generate_pattern_file', metavar='LENGTH',
                          help='generate a pattern file for a pattern of LENGTH motifs')
    generate_pattern_file.add_option('-f', '--pattern_filepath', dest='pattern_file_path',
                          help='where to write the pattern file [default: %default]')
    parser.add_option_group(generate_pattern_file)
    
    genome_group = OptionGroup(parser, 'Run on a genome', 'These options are respected when Figmop is run in its default mode, scanning a genome for instances of some sequence pattern.')
    genome_group.add_option('-p', '--sequence_padding', dest='sequence_padding',
                      type='int', metavar='LENGTH',
                      help='save and additional LENGTH bp on either side of a match')
    genome_group.add_option('-x', '--default_mast_xml', dest='default_mast_xml', metavar='FILENAME',
                      help='default name of the MAST output xml file [default: %default]')
    parser.add_option_group(genome_group)
    
    model_group = OptionGroup(parser, 'Model options', 'These are typically set in the pattern file. Any options set here will override those in the pattern file.')
    model_group.add_option('-m', '--min_matches', type='int', dest='min_matches',
                           help='minimum number of motifs to qualify as a hit [default: half the length of the pattern]')
    model_group.add_option('-l', '--max_genome_region', type='int', dest='max_genome_region',
                           help='a hit must be shorter than this on the genome [default: 40000 bp]')
    model_group.add_option('--meme_file', dest='meme_file',
                           help='path to a meme.txt file to use with the model')
    parser.add_option_group(model_group)
    return parser

def validate_prot_options(prot_file, parser, args):
    if not os.path.isfile(prot_file):
        parser.error('no protein sequence file found at %s' % prot_file)
    if len(args) != 1:
        parser.error('the MEME_FILE argument must be supplied if the --prot flag is used')
    meme_file = args[0]
    if os.path.isdir(meme_file):
        meme_file = os.path.join(meme_file, 'meme.txt')
    if not os.path.isfile(meme_file) or not meme_file.endswith('.txt'):
        parser.error('could not locate a meme.txt file at %s' % meme_file)
    return os.path.realpath(prot_file), os.path.realpath(meme_file)
def validate_model_options(parser, options):
    e_value = options.e_value
    if e_value <= 0: parser.error('e_value must be >= 0')
    mm = options.min_matches
    mgr = options.max_genome_region
    mf = options.meme_file
    if mm and mm < 0: parser.error('min_matches must be >= 0')
    if mgr < 0: parser.error('max_genome_region must be > 0, and is typically >> 1000')
    if mf:
        if not (os.path.isfile(mf) and mf.endswith('.txt')): parser.error('meme_file must be the .txt file generated by MEME')
        mf = os.path.realpath(mf)
    return e_value, mm, mgr, mf
def validate_genome_options1(parser, args):
    if len(args) != 3: parser.error('must supply PATTERN_FILE, GENOME_FILE, and GENOME_MAST_DIR to run Figmop on a genome')
    pattern_file, genome_file, genome_mast_dir = args
    pattern_file = os.path.realpath(pattern_file)
    if not pattern_file.endswith('.py') or not os.path.isfile(pattern_file):
        parser.error('PATTERN_HMM must be a valid patternHmm model file.')
    try:
        model_path, model_name = os.path.split(pattern_file)
        sys.path.append(model_path)
        model_module = __import__(model_name[:-3])
    except (ImportError, AttributeError):
        parser.error("the model could not be imported from %s." % pattern_file)
    if not os.path.isfile(genome_file): parser.error('GENOME_FILE must be a FASTA formatted sequence file')
    return genome_file, os.path.realpath(genome_mast_dir), model_module
def validate_genome_options2(model_module, min_matches, max_genome_region, meme_file, parser, options):
    sequence_padding = options.sequence_padding
    if sequence_padding < 0: parser.error('sequence_padding must be >= 0')
    if not min_matches:
        min_matches = getattr(model_module, 'min_matches', 0)
    if not max_genome_region:
        max_genome_region = getattr(model_module, 'max_genome_region', 40000)
    if not meme_file:
        meme_file = getattr(model_module, 'meme_file', '')
        if not meme_file or not os.path.isfile(meme_file):
            parser.error("a MEME file must be provided in the model file or at the command line, but none was found at '%s'" % meme_file)
    return sequence_padding, min_matches, max_genome_region, meme_file, model_module.model


def main():
    parser = setup_parser()
    (options, args) = parser.parse_args()
    # Validate some initial options and arguments
    e_value, min_matches, max_genome_region, meme_file = validate_model_options(parser, options)
    new_model_len, prot_file = options.generate_pattern_file, options.prot_file
    
    if prot_file:       ###  Mode 1: Run Figmop on protein sequences.
        prot_file, meme_file = validate_prot_options(prot_file, parser, args)
        run_mast(meme_file, prot_file, options.output_dir, e_value, False)
        output_seq_file = os.path.join(options.output_dir, options.hits_filename)
        extract_seqs(options.output_dir, prot_file, output_seq_file)
    elif new_model_len: ###  Mode 2: Generate a new pattern file.
        if new_model_len < 2:
            parser.error('the length of the model file must be > 1')
        pattern_file = options.pattern_file_path
        if not pattern_file.endswith('.py'): pattern_file += '.py'
        create_pattern_file(new_model_len, pattern_file, min_matches, max_genome_region, meme_file)
        return
    else:               ###  Mode 3: Run Figmop on a genome.
        genome_file, genome_mast_dir, model_module = validate_genome_options1(parser, args)
        sequence_padding, min_matches, max_genome_region, meme_file, model = validate_genome_options2(model_module, min_matches, max_genome_region, meme_file, parser, options)
        #  Run MAST on the genome file:
        if not os.path.isdir(genome_mast_dir) or not os.path.isfile(os.path.join(genome_mast_dir, options.default_mast_xml)):  # Run MAST on the genome before running FiGMoP
            print "\nRunning MAST on the sequence file '%s' using the motifs from the MEME file '%s'\n" % (genome_file, meme_file)
            run_mast(meme_file, genome_file, genome_mast_dir, 1000)
        # Find patterns of sequence motifs:
        print "\nRunning FiGMoP on the genomic motifs from '%s' using the pattern file '%s'\n" % (genome_mast_dir, args[0])
        patterns = MotifPatterns(genome_mast_dir, model, genome_file, min_matches,
                                        sequence_padding)
        patterns.run_mast_on_patterns(meme_file, max_genome_region, e_value,
                                      options.output_dir, options.hits_filename)
if __name__ == "__main__":
    main()
